modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/The-Fireplace-Minecraft-Mods/Grand-Economy/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/grand-economy"
credits=""
authors="The_Fireplace"

[[mods]] #mandatory
modId="grandeconomy"
version="${file.jarVersion}"
displayName="Grand Economy"
description='''
A server-side economy mod/api that supports using currency from sponge/forgeessentials/vault/others.
'''

[[dependencies.grandeconomy]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.grandeconomy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="SERVER"